name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.2.1
        with:
          hugo-version: latest

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Prepare local theme
        run: |
          mkdir -p exampleSite/themes/hugo-bearblog
          cp -R archetypes images layouts theme.toml exampleSite/themes/hugo-bearblog/

      - name: Build local ./exampleSite
        run: hugo --minify --gc --destination ../public --source ./exampleSite --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

  deploy:
    needs: build
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
